### ISSUE TITLE
Build-TocHereRecursive wasn't found in ExportedCommands

### ISSUE THREAD

**Issue by BennyKok** [0xaryan/docfx-toc-generator#1]
I installed PowerShell core 7.1, and the two modules stated in the readme `Install-Module powershell-yaml` `Install-Module -Name docfx-toc-generator    `, however `Build-TocHereRecursive` wasn't appearing in the ExportedCommands 

![image](https://user-images.githubusercontent.com/18395202/99872045-e1db9200-2c19-11eb-9f35-e358c56f0c9d.png)
![image](https://user-images.githubusercontent.com/18395202/99872194-eeacb580-2c1a-11eb-9fe0-f4bb23180592.png)

I'm fairly new to using powershell, so it could be me misunderstood something...

**Comment by viclin-msft** [comment]
Same issue here, PowerShell 7.1.3

**Comment by jmkloz** [comment]
Had the same issue as well, had to import by pointing to the docfx-toc-generator.psm1. Root module isn't specified explicitly in the .psd1 file
`Import-Module $env:ProgramFiles\PowerShell\Modules\docfx-toc-generator\1.1\docfx-toc-generator.psm1`

**Comment by avestura** [comment]
Thanks to @DrJMKatz, it must work now (https://www.powershellgallery.com/packages/docfx-toc-generator/1.2)
